---

- name: 'linux apps docker : install extension script'
  become: true
  get_url:
    url: >-
      https://raw.githubusercontent.com/librenms/librenms-agent/master/snmp/docker-stats.py
    dest: '{{ snmp_application_extension_scripts }}/docker-stats.py'
    owner: root
    group: "{{ snmp_deamon_group | default('root') }}"
    mode: '0755'
    seuser: system_u
    serole: object_r
    setype: lib_t
    selevel: s0
  when: snmp_application_discovery.docker

- name: 'linux apps docker : allow daemon docker access'
  become: true
  user:
    name: '{{ snmp_deamon_user }}'
    groups: docker
    append: true
  when:
    - snmp_application_discovery.docker
    - snmp_deamon_user is defined
  notify:
    - restart snmp

- name: 'linux apps docker : install snmpd include snippet'
  become: true
  copy:
    content: >
      {{ 'extend docker /bin/python3 '
         ~ snmp_application_extension_scripts ~ '/docker-stats.py' }}
    dest: '{{ snmp_config_include_dir }}/docker.conf'
    owner: root
    group: root
    mode: '0640'
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0
  when: snmp_application_discovery.docker
  notify:
    - restart snmp

- name: 'linux apps docker : remove stale snmpd include snippet'
  become: true
  file:
    path: '{{ snmp_config_include_dir }}/docker.conf'
    state: absent
  when: not snmp_application_discovery.docker
  notify:
    - restart snmp
