---

- name: 'linux apps fail2ban : install extension script'
  become: true
  get_url:
    url: >-
      https://raw.githubusercontent.com/librenms/librenms-agent/master/snmp/fail2ban
    dest: '{{ snmp_application_extension_scripts }}/fail2ban'
    owner: root
    group: "{{ snmp_deamon_group | default('root') }}"
    mode: '0755'
    seuser: system_u
    serole: object_r
    setype: lib_t
    selevel: s0
  when: snmp_application_discovery.fail2ban

- name: 'linux apps fail2ban : install snmpd include snippet'
  become: true
  copy:
    content: |
      extend fail2ban {{ snmp_application_extension_scripts }}/fail2ban
    dest: '{{ snmp_config_include_dir }}/fail2ban.conf'
    owner: root
    group: root
    mode: '0640'
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0
  when: snmp_application_discovery.fail2ban
  notify:
    - restart snmp

- name: 'linux apps fail2ban : remove stale snmpd include snippet'
  become: true
  file:
    path: '{{ snmp_config_include_dir }}/fail2ban.conf'
    state: absent
  when: not snmp_application_discovery.fail2ban
  notify:
    - restart snmp
