---

- name: 'linux apps nvidia_gpu : install extension script'
  become: true
  get_url:
    url: >-
      https://raw.githubusercontent.com/librenms/librenms-agent/master/snmp/nvidia
    dest: '{{ snmp_application_extension_scripts }}/nvidia'
    owner: root
    group: "{{ snmp_deamon_group | default('root') }}"
    mode: '0755'
    seuser: system_u
    serole: object_r
    setype: lib_t
    selevel: s0
  when: snmp_application_discovery.nvidia_gpu

- name: 'linux apps nvidia_gpu : install snmpd include snippet'
  become: true
  template:
    src: snmp/nvidia_gpu.conf.j2
    dest: '{{ snmp_config_include_dir }}/nvidia_gpu.conf'
    owner: root
    group: root
    mode: '0640'
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0
  when: snmp_application_discovery.nvidia_gpu
  notify:
    - restart snmp

- name: 'linux apps nvidia_gpu : remove stale snmpd include snippet'
  become: true
  file:
    path: '{{ snmp_config_include_dir }}/nvidia_gpu.conf'
    state: absent
  when: not snmp_application_discovery.nvidia_gpu
  notify:
    - restart snmp
