---

- name: 'linux apps smart : install extension script'
  become: true
  get_url:
    url: >-
      https://raw.githubusercontent.com/librenms/librenms-agent/master/snmp/smart-v1
    dest: '{{ snmp_application_extension_scripts }}/smart'
    owner: root
    group: "{{ snmp_deamon_group | default('root') }}"
    mode: '0755'
    seuser: system_u
    serole: object_r
    setype: lib_t
    selevel: s0
  when: snmp_application_discovery.smart

- name: 'linux apps smart : install snmpd include snippet'
  become: true
  copy:
    content: |
      extend smart /bin/cat /var/cache/smart
    dest: '{{ snmp_config_include_dir }}/smart.conf'
    owner: root
    group: root
    mode: '0640'
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0
  when: snmp_application_discovery.smart
  notify:
    - restart snmp

- name: 'linux apps smart : remove stale snmpd include snippet'
  become: true
  file:
    path: '{{ snmp_config_include_dir }}/smart.conf'
    state: absent
  when: not snmp_application_discovery.smart
  notify:
    - restart snmp
