---
# tasks file for sbaerlocher.snmp
- name: test
  setup:

- name: add OS specific variables
  include_vars: "{{ loop_vars }}"
  with_first_found:
    - files:
        - >-
          {{ ansible_facts['lsb']['id'] ~ '-'
             ~ ansible_facts['distribution_release'] ~ '.yml' }}
        - "{{ ansible_facts['lsb']['id'] }}.yml"
        - >-
          {{ ansible_facts['distribution'] ~ '-'
             ~ ansible_facts['distribution_version'] ~ '.yml' }}
        - >-
          {{ ansible_facts['distribution'] ~ '-'
             ~ ansible_facts['distribution_major_version'] ~ '.yml' }}
        - "{{ ansible_facts['distribution'] }}.yml"
        - "{{ ansible_facts['os_family'] }}.yml"
        - "{{ ansible_facts['system'] }}.yml"
        - "defaults.yml"
      paths:
        - "vars"
  loop_control:
    loop_var: loop_vars
  tags:
    - configuration
    - packages

- name: detect Raspberry Pi hardware
  stat:
    path: /sys/firmware/devicetree/base/model
  register: snmp_rpi_devicetree
  when: ansible_facts['system'] == 'Linux'

- name: load Raspberry Pi variable overrides
  include_vars: "vars/Raspbian.yml"
  when:
    - ansible_facts['system'] == 'Linux'
    - snmp_rpi_devicetree.stat is defined
    - snmp_rpi_devicetree.stat.exists

- name: include distribution tasks
  include_tasks: "{{ loop_distribution }}"
  with_first_found:
    - files:
        - >-
          {{ ansible_facts['lsb']['id'] ~ '-'
             ~ ansible_facts['distribution_release'] ~ '.yml' }}
        - "{{ ansible_facts['lsb']['id'] }}.yml"
        - >-
          {{ ansible_facts['distribution'] ~ '-'
             ~ ansible_facts['distribution_version'] ~ '.yml' }}
        - >-
          {{ ansible_facts['distribution'] ~ '-'
             ~ ansible_facts['distribution_major_version'] ~ '.yml' }}
        - "{{ ansible_facts['distribution'] }}.yml"
        - "{{ ansible_facts['os_family'] }}.yml"
        - "{{ ansible_facts['system'] }}.yml"
        - "defaults.yml"
      paths:
        - "distribution"
  loop_control:
    loop_var: loop_distribution
  tags:
    - configuration
    - packages
